#!/bin/bash

/apps/fedora/scripts/checkuser || exit 1

configure_ssl() {
    if [ ! -f /apps/fedora/.ssl_configured ]; then
        echo
        echo "Configure SSL certificates for tomcat and karaf"
        cd /apps/fedora/scripts/
        ./sslsetup.sh
        cd -
        touch /apps/fedora/.ssl_configured
        echo
    fi
}

initialize_repo() {
    if [ ! -f /apps/fedora/.initialized ]; then
        echo
        echo "Initialize the repository"
        /apps/fedora/scripts/initialize.sh
        touch /apps/fedora/.initialized
        echo
    fi
}

case "$1" in
  start)
    echo === Starting Fedora ===
    echo start: `/bin/date` >> control.log
    configure_ssl
    (cd fuseki; ./control start)
    (cd tomcat; ./control start)
    (cd karaf; ./control start)
    (cd apache; ./control start)
    initialize_repo
    ;;

  stop)
    echo === Stopping Fedora ===
    echo 'stop: ' `/bin/date` >> control.log
    (cd apache; ./control stop)
    (cd karaf; ./control stop)
    (cd tomcat; ./control stop)
    (cd fuseki; ./control stop)
    ;;

  restart)
    ./control stop
    sleep 5
    ./control start
    ;;

  *)
    echo invalid option
    ;;

esac
